[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38/platform-espressif32.zip
framework = arduino
board = seeed_xiao_esp32c6

board_build.partitions = partitions.csv
board_build.flash_mode = dio

lib_deps =
    h2zero/NimBLE-Arduino@^2.5.0
    bblanchon/ArduinoJson@^6.21.2
    https://github.com/ivanseidel/LinkedList.git
    adafruit/Adafruit SH110X@^2.1.8
    adafruit/Adafruit GFX Library@^1.11.9

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -w
    -Wl,-zmuldefs
