[platformio]




[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38/platform-espressif32.zip
framework = arduino

board_build.partitions = partitions.csv
board_build.flash_mode = dio

lib_deps =
    bblanchon/ArduinoJson@^6.21.2
    https://github.com/ivanseidel/LinkedList.git

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DADBLOCK32_ENABLE_DISPLAY=0
    -w
    -Wl,-zmuldefs

[env:seeed_xiao_esp32c6]
board = seeed_xiao_esp32c6

[env:seeed_xiao_esp32c6_display]
board = seeed_xiao_esp32c6
lib_deps =
    ${env.lib_deps}
    adafruit/Adafruit SH110X@^2.1.8
    adafruit/Adafruit GFX Library@^1.11.9
build_flags =
    ${env.build_flags}
    -DADBLOCK32_ENABLE_DISPLAY=1
